### PR TITLE
CONFIG: NAS-5344 Bump image version to process also fast_track branch

### PR DESCRIPTION
**Pull request by jeskepetr**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/154/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/163/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/155/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/164/ : SUCCESS in 4s

**Review by mouchar — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/156/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/165/ : SUCCESS in 5s

**Review by mouchar — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR76

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/157/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/65/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/63/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/26/ : FAILURE in 6s (non-voting)

**Pull request merged**
