### PR TITLE
test validation

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- gooddata-public-demos-validation : NOT_REGISTERED
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/62/ : SUCCESS in 7s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- gooddata-public-demos-validation : NOT_REGISTERED
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/63/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- gooddata-public-demos-validation : NOT_REGISTERED
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/64/ : SUCCESS in 8s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/44/ : FAILURE in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/65/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/46/ : FAILURE in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/67/ : SUCCESS in 11s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/47/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/68/ : SUCCESS in 6s

**Pull request closed without merging**
