### PR TITLE
Correct readme link for workspace analytics

### PR DESCRIPTION
**Pull request by kandl**
- Now, the link leads to non-existing/removed file

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/87/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/97/ : SUCCESS in 6s

**Review by andriichumak — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR42

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/88/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/40/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/38/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/1/ : SUCCESS in 44s (non-voting)

**Pull request merged**
