### PR TITLE
MPNT-58: update README file

### PR DESCRIPTION
**Pull request by tvthuan210**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/48/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/69/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build in pipeline gate aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/49/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/70/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/50/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/71/ : SUCCESS in 10s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR22

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/51/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/22/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/20/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul-el7/20/ : SUCCESS in 51s (non-voting)

**Pull request merged**
