### PR TITLE
FEATURE: MPNT-112 Temporary allow trigger CI pipeline manually

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/70/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/82/ : SUCCESS in 6s

**Comment by helobinvn** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR32

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/71/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/31/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/29/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul-el7/29/ : SUCCESS in 42s (non-voting)

**Pull request merged**
