### PR TITLE
INFRA-1275: Switch Tiger-dev ECR to Infra1

### PR DESCRIPTION
**Pull request by helobinvn**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/195/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/202/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/196/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/203/ : SUCCESS in 3s

**Review by huavannis — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR85

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/197/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/73/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/71/ : SUCCESS in 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/34/ : FAILURE in 9s (non-voting)

**Pull request merged**
