### PR TITLE
FEATURE: MPNT-103, MPNT-106 Add postgresql.ddl and Support create workspaceDataFilters for workspace

### PR DESCRIPTION
**Pull request by huavannis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/74/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/84/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/75/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/85/ : SUCCESS in 5s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR34

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/33/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/31/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul-el7/31/ : SUCCESS in 47s (non-voting)

**Pull request merged**
