### PR TITLE
Revert "FEATURE: MPNT-112 Temporary allow trigger CI pipeline manually"

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**
Reverts gooddata/gooddata-public-demos#32

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/72/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/83/ : SUCCESS in 6s

**Comment by helobinvn** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR33

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/73/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/32/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/30/ : SUCCESS in 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul-el7/30/ : SUCCESS in 49s (non-voting)

**Pull request merged**
