### PR TITLE
BUGFIX: SD-2847 Update ecommerce demo data

### PR DESCRIPTION
**Pull request by thuytran-gooddata**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/133/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/140/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/134/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/141/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/144/ : SUCCESS in 4s

**Comment by anvuong119** [comment]
LGTM

**Review by huavannis — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR68

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/60/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/58/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/21/ : FAILURE in 16s (non-voting)

**Pull request merged**
