### PR TITLE
FEATURE: SD-2645 Update dashboards with new charts and interactivity

### PR DESCRIPTION
**Pull request by thuytran-gooddata**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/115/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/122/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/116/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/123/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/117/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/124/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/118/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/125/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/119/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/126/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/120/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/127/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/121/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/128/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/122/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/129/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/123/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/130/ : SUCCESS in 4s

**Comment by anvuong119** [comment]
LGTM

**Review by huavannis — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR64

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/124/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/57/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/55/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/18/ : FAILURE in 5s (non-voting)

**Pull request merged**
