### PR TITLE
FEATURE: CAL-892 Support compatibility PDM Removal

### PR DESCRIPTION
**Pull request by thuytran-gooddata**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/125/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/131/ : SUCCESS in 4s

**Review by huavannis — COMMENTED** [review]
- Replace `"dataSourceId": "gdc_ds_gooddemo"` by `"dataSourceId": "gdc_ds_ecommerce_demo"`
- Replace `ECOMMERCE_DEMO_SCHEMA1` by `ECOMMERCE_DEMO_SCHEMA`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/126/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/132/ : SUCCESS in 4s

**Comment by thuytran-gooddata** [comment]
> * ECOMMERCE_DEMO_SCHEMA1

I updated it thank you

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/131/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/138/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/132/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/139/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/136/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/145/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/137/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/146/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/138/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/147/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/139/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/148/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/140/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/149/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/141/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/150/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/142/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/151/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/159/ : SUCCESS in 5s

**Review by huavannis — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR65

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/63/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/61/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/24/ : FAILURE in 6s (non-voting)

**Pull request merged**
