### PR TITLE
chore: merge release branch into master as part of P33.0 CodeDrop

### PR DESCRIPTION
**Pull request by thuytran-gooddata**
JIRA: DC-3054

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/194/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/201/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/198/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/205/ : SUCCESS in 3s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR84

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/201/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/75/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/73/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/36/ : FAILURE in 5s (non-voting)

**Pull request merged**
