### PR TITLE
BUGFIX: SD-2891 AIO - Can not show insight when drilling data

### PR DESCRIPTION
**Pull request by thuytran-gooddata**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/135/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/142/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/143/ : SUCCESS in 6s

**Comment by anvuong119** [comment]
LGTM

**Review by huavannis — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR69

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/59/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/57/ : SUCCESS in 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul/20/ : FAILURE in 5s (non-voting)

**Pull request merged**
