### PR TITLE
Merge back release branch to master

### PR DESCRIPTION
**Pull request by danh-ung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/84/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/94/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/85/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-oss-check/96/ : SUCCESS in 10s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-public-demos-gate-PR40

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-public-demos/job/gooddata-public-demos-validation/86/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-merge-compliance-check/39/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-sonarqube-scan-zuul-gate/37/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-public-demos-fossa-scanning-zuul-el7/37/ : SUCCESS in 1m 04s (non-voting)

**Pull request merged**
